### PR TITLE
gamma-conversion 

### PR DESCRIPTION
**Pull request by sunanda15**
To enable the gamma-conversion generator in WCSim (https://github.com/nickwp/WCSim/compare/01cc7e4d..8c414f4a)

   1. For gammas, gamma-conversion is usually used to initially generate events in the centre of the tank until they convert into a positron and electron.
   2.  It will then simulate the positron and electron starting again from the original position to produce the final output.
   3. Thus gamma events are considered to convert at the specified position rather than produced at that position, to provide unbiased comparisons with electron events.

### CODE REVIEW

**Comment by sunanda15** [comment]
# To enable the gamma-conversion generator in WCSim (https://github.com/nickwp/WCSim/compare/01cc7e4d..8c414f4a)
1. For gammas, gamma-conversion is usually used to initially generate events in the centre of the tank until they convert into a positron and electron.
2. It will then simulate the positron and electron starting again from the original position to produce the final output.
3. Thus gamma events are considered to convert at the specified position rather than produced at that position, to provide unbiased comparisons with electron events.

**Review by pdeperio — CHANGES_REQUESTED** [review]
Please also include a simple diagram with your description. And validation plots to show that it's working as expected.

**Review by nickwp — APPROVED** [review]
This looks fine to me, should work identically to the gamma conversion setup we used for IWCD ML studies, since these code changes are identical to those we made in that branch.
Just as an extra check, have you tried to use this version to generate gamma-conversion events? Could you generate a small number of gamma-conversion events at a fixed location, then check the output truth information that it genuinely simulates the electron and positron starting from that desired position?

**Comment by sunanda15** [comment]
> Please also include a simple diagram with your description. And validation plots to show that it's working as expected.

Okay, I will add it.

**Comment by sunanda15** [comment]
> Please also include a simple diagram with your description. And validation plots to show that it's working as expected.

 The below Feynman diagram represents the conversion of gamma into electron and positron.
gammim
Figure1.1 gamma converts at the specific position corresponding to the vertex and gamma conversion simulates the positron and electron starting from this point. Details of Data production are given here (https://www.watchmal.org/computing/software-resources/data-production)

**Comment by sunanda15** [comment]
> This looks fine to me, should work identically to the gamma conversion setup we used for IWCD ML studies, since these code changes are identical to those we made in that branch. Just as an extra check, have you tried to use this version to generate gamma-conversion events? Could you generate a small number of gamma-conversion events at a fixed location, then check the output truth information that it genuinely simulates the electron and positron starting from that desired position?

Yes, I have checked this version to generate gamma-conversion events.  The validation plots of a small number of gamma-conversion events at a fixed location(x=0,y=0,z=0 and direction =4pi and Energy =1 to 1000 MeV) are shown below 
y_gamma   x_gamma
z_gamma      zdir_gamma
ydir_gamma  xdir_gamma
energy_gamma

**Review by pdeperio — APPROVED** [review]

**Review by nickwp — APPROVED** [review]

**Review by laurenanthony2 — APPROVED** [review]
At some point we should update the WCTE README with info on the new functionalities.

**Pull request merged**
